Repository vavarm/Carmageddon, pull requests merged in 2024-03, with the labels that each got.

#17 14 create frontend
  frontend/.env.development
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.jsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/vite.config.js
  frontend/yarn.lock
  src/main/resources/META-INF/resources/DEV-FRONTEND/index.html
  src/main/resources/application.properties
Labels: enhancement

#16 15 create services
  .gitignore
  src/main/java/org/acme/common/Calculation.java
  src/main/java/org/acme/ctrl/GameController.java
  src/main/java/org/acme/ctrl/VehicleController.java
  src/main/java/org/acme/dto/CreateGameDTO.java
  src/main/java/org/acme/model/Cell.java
  src/main/java/org/acme/model/Vehicle.java
  src/main/java/org/acme/svc/GameService.java
  src/main/java/org/acme/svc/VehicleService.java
  src/main/java/org/acme/svc/impl/GameServiceImpl.java
  src/main/java/org/acme/svc/impl/VehicleServiceImpl.java
  src/test/java/org/acme/common/CalculationTest.java
  src/test/java/org/acme/ctrl/GameControllerTest.java
  src/test/java/org/acme/ctrl/VehicleControllerTest.java
  src/test/java/org/acme/dto/CreateGameDTOTest.java
  src/test/java/org/acme/svc/impl/VehicleServiceImplTest.java
Labels: enhancement

#19 18 link frontend and backend
  build.gradle
  frontend/src/App.jsx
  gradle.properties
  paho4896856521833-wsmqtteclipseprojectsiomqtt/.lck
  paho4897701535875-wsmqtteclipseprojectsiomqtt/.lck
  paho4898325012958-wsmqtteclipseprojectsiomqtt/.lck
  paho4898939282416-wsmqtteclipseprojectsiomqtt/.lck
  paho5197285233333-wsmqtteclipseprojectsiomqtt/.lck
  paho5197974876708-wsmqtteclipseprojectsiomqtt/.lck
  paho5198625019375-wsmqtteclipseprojectsiomqtt/.lck
  paho5199242465625-wsmqtteclipseprojectsiomqtt/.lck
  src/main/java/org/acme/ctrl/GameController.java
  src/main/java/org/acme/ctrl/VehicleController.java
  src/main/java/org/acme/dto/CreateVehicleDTO.java
  src/main/java/org/acme/model/Game.java
  src/main/java/org/acme/svc/MQTTService.java
  src/main/java/org/acme/svc/impl/MQTTServiceImpl.java
  src/main/java/org/acme/svc/impl/VehicleServiceImpl.java
  src/test/java/org/acme/ctrl/VehicleControllerTest.java
  src/test/java/org/acme/model/GameTest.java
Labels: enhancement

#23 feat: add compiler files
  src/main/java/org/acme/Compiler.java
  src/main/java/org/acme/compiled/Calculation.java
  src/main/toBeCompiled/method1.compil
  src/main/toBeCompiled/method2.badcompil
  src/main/toBeCompiled/moins.compil
  src/main/toBeCompiled/plus.compil
  src/main/toBeCompiled/zero.compil
Labels: enhancement

#26 build: replace the quarkus frontend with our frontend
  frontend/.env.production
  frontend/index.html
  frontend/public/car.svg
  frontend/vite.config.js
  src/main/resources/META-INF/resources/assets/index-BPvgi06w.css
  src/main/resources/META-INF/resources/assets/index-BYyNFRxD.js
  src/main/resources/META-INF/resources/car.svg
  src/main/resources/META-INF/resources/index.html
  src/main/resources/META-INF/resources/vite.svg
Labels: build

#30 Update README.md
  README.md
Labels: documentation

#32 Update gradle.yml
  .github/workflows/gradle.yml
Labels: build
